spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost/test?autoReconnect=true&useSSL=false
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: test
    password: P@ssword1!
logging:
  file: logs/application-debug.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    ROOT: INFO
    org.springframework.web: ERROR
    org.hibernate: ERROR
